vich_uploader:
    db_driver: orm

    mappings:
        offres_img:
            uri_prefix: /uploads/images/offres
            upload_destination: '%kernel.project_dir%/public/uploads/images/offres'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            
        companies_img:
            uri_prefix: /uploads/images/companies
            upload_destination: '%kernel.project_dir%/public/uploads/images/companies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        companies_documents:
            uri_prefix: '%app.path.companies_documents%'
            upload_destination: '%kernel.project_dir%/public%app.path.companies_documents%'

        rib_files:
            uri_prefix: '%app.path.rib_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.rib_files%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        cni_files:
            uri_prefix: '%app.path.cni_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.cni_files%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
